log_level: "INFO"
job: "pg-scrape-auto"
local_log_dir: "../tmp/logs"
s3_bucket: "pg-scrape-auto"
gcs_bucket: "pg-scrape-auto-tmp"
gcs_sa_creds: "creds/gcp_sa.json"
raw_zip_s3_prefix: "02_zipped"
transformed_s3_prefix: "03_transformed"
analysis_s3_prefix: "04_analysis"
